select * from alumno;
insert into alumno (Nombre,DNI,Fecha_Nac,EMail) values ("Manuel",6849846,"1984-08-14","manUuU@gmail.com");
insert into alumno (Nombre,DNI,Fecha_Nac,EMail) values ("Miguela",6849847,"1986-05-21","miguela@gmail.com");
insert into alumno (Nombre,DNI,Fecha_Nac,EMail) values ("Rosalía",6849848,"1977-02-19","manUuU@gmail.com");
select * from curso;
insert into curso (Nombre) values ("Astronomía");
insert into curso (Nombre) values ("Gastronomía Mística");
insert into curso (Nombre) values ("Estudio de Ciencias Cienciosas");
select * from profesor;
insert into profesor (Nombre,Especialidad,EMail) values ("Alberto","Astronomía","profealbert@gmail.com");
insert into profesor (Nombre,Especialidad,EMail) values ("Julio","Gastronomía Mística","profeJunio@gmail.com");
insert into profesor (Nombre,Especialidad,EMail) values ("Olivia","Estudio de Ciencias Cienciosas","profeOlivia@gmail.com");
select * from realiza_curso;
insert into realiza_curso (Cod_Matricula,Cod_Curso) values (1,3);
insert into realiza_curso (Cod_Matricula,Cod_Curso) values (2,1);
insert into realiza_curso (Cod_Matricula,Cod_Curso) values (3,2);
select * from dictado_por;
insert into dictado_por (Cod_Curso,Profesor_Id) values (1,1);
insert into dictado_por (Cod_Curso,Profesor_Id) values (2,2);
insert into dictado_por (Cod_Curso,Profesor_Id) values (3,3);
